#!/bin/bash


echo "
alias bdu='srch bdu'
alias bg='srch bg'
alias duck='srch duck'
alias g='srch g'
alias yah='srch yah'
alias yx='srch yx'
alias o='srch -l'" >> ~/.bashrc
echo "Now you can use just search engine's reduction or 'lo link.com' if you want to open a website"
